"""add_users_and_api_keys

Revision ID: 39b9ba168b2e
Revises: 1bafdf7d488b
Create Date: 2026-08-16 04:35:28.026755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b9ba168b2e'
down_revision: Union[str, Sequence[str], None] = '1bafdf7d488b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.execute("""
        INSERT INTO users (id, email, is_active)
        SELECT DISTINCT user_id, 'legacy_' || user_id || '@freightpulse.test', true
        FROM (
            SELECT user_id FROM rate_alert_rules
            UNION
            SELECT user_id FROM rate_alerts
            UNION
            SELECT user_id FROM route_briefs
        ) AS existing_users
        ON CONFLICT DO NOTHING
    """)

    op.create_foreign_key('fk_rate_alert_rules_user_id', 'rate_alert_rules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_rate_alerts_user_id', 'rate_alerts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_route_briefs_user_id', 'route_briefs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_route_briefs_user_id', 'route_briefs', type_='foreignkey')
    op.drop_constraint('fk_rate_alerts_user_id', 'rate_alerts', type_='foreignkey')
    op.drop_constraint('fk_rate_alert_rules_user_id', 'rate_alert_rules', type_='foreignkey')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
