"""restore users table

Revision ID: 685a898ec4cf
Revises: 7cd5c016de3f
Create Date: 2026-08-20 20:49:20.787971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685a898ec4cf'
down_revision: Union[str, Sequence[str], None] = '7cd5c016de3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('rate_alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trade_lane', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('magnitude_pct', sa.Float(), nullable=True),
    sa.Column('target_usd', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_rules_lane', 'rate_alert_rules', ['trade_lane'], unique=False)
    op.create_index('idx_alert_rules_user_active', 'rate_alert_rules', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_rate_alert_rules_user_id'), 'rate_alert_rules', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('rate_alerts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('rate_trends', sa.Column('status',sa.String(),nullable=False,server_default='none'))
    op.add_column('rate_trends', sa.Column('outlook_text', sa.String(), nullable=True))
    op.add_column('rate_trends', sa.Column('recommendation', sa.String(), nullable=True))
    op.add_column('rate_trends', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('rate_trends', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('rate_trends', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rate_trends', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_trends_status', 'rate_trends', ['status'], unique=False)
    op.add_column('route_briefs', sa.Column('carrier', sa.String(), nullable=True))
    op.add_column('route_briefs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_briefs', 'updated_at')
    op.drop_column('route_briefs', 'carrier')
    op.drop_index('idx_trends_status', table_name='rate_trends')
    op.drop_column('rate_trends', 'created_at')
    op.drop_column('rate_trends', 'updated_at')
    op.drop_column('rate_trends', 'error_message')
    op.drop_column('rate_trends', 'confidence')
    op.drop_column('rate_trends', 'recommendation')
    op.drop_column('rate_trends', 'outlook_text')
    op.drop_column('rate_trends', 'status')
    op.alter_column('rate_alerts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rate_alert_rules_user_id'), table_name='rate_alert_rules')
    op.drop_index('idx_alert_rules_user_active', table_name='rate_alert_rules')
    op.drop_index('idx_alert_rules_lane', table_name='rate_alert_rules')
    op.drop_table('rate_alert_rules')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index('idx_api_keys_user_id', table_name='api_keys')
    op.drop_index('idx_api_keys_hash', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
