"""add_historical_persistence

Revision ID: 7a3b421a2c3d
Revises: 632b289e025b
Create Date: 2026-10-01 17:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a3b421a2c3d'
down_revision: Union[str, None] = '632b289e025b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bunker_rates',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('port_name', sa.String(), nullable=False),
        sa.Column('fuel_type', sa.String(), nullable=False),
        sa.Column('price_usd', sa.Float(), nullable=False),
        sa.Column('observed_date', sa.Date(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('port_name', 'fuel_type', 'observed_date', name='uq_bunker_rate')
    )
    op.create_index('idx_bunker_rates_date', 'bunker_rates', ['observed_date'], unique=False)
    op.create_index('idx_bunker_rates_port', 'bunker_rates', ['port_name'], unique=False)

    op.create_table('exchange_rates',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('base_currency', sa.String(), nullable=False),
        sa.Column('quote_currency', sa.String(), nullable=False),
        sa.Column('exchange_rate', sa.Float(), nullable=False),
        sa.Column('observed_date', sa.Date(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('base_currency', 'quote_currency', 'observed_date', name='uq_exchange_rate')
    )
    op.create_index('idx_exchange_rates_date', 'exchange_rates', ['observed_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exchange_rates_date', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index('idx_bunker_rates_port', table_name='bunker_rates')
    op.drop_index('idx_bunker_rates_date', table_name='bunker_rates')
    op.drop_table('bunker_rates')
    # ### end Alembic commands ###
