"""add new columns

Revision ID: 7cd5c016de3f
Revises: 7ca940718346
Create Date: 2026-08-18 05:07:24.723063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cd5c016de3f'
down_revision: Union[str, Sequence[str], None] = '7ca940718346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""

    # Remove foreign keys first
    op.drop_constraint(
        'fk_rate_alerts_rule_id',
        'rate_alerts',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_rate_alerts_user_id',
        'rate_alerts',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_route_briefs_user_id',
        'route_briefs',
        type_='foreignkey',
    )

    # Old tables that depend on users
    op.drop_table('api_keys')

    op.drop_index(
        'idx_rules_user_active',
        table_name='rate_alert_rules',
    )

    op.drop_table('rate_alert_rules')

    # Now users can be removed safely
    op.drop_index(
        'ix_users_email',
        table_name='users',
    )

    op.drop_table('users')

    # --------------------------------------------------
    # rate_alerts
    # --------------------------------------------------

    op.add_column(
        'rate_alerts',
        sa.Column('direction', sa.String(), nullable=True),
    )

    op.add_column(
        'rate_alerts',
        sa.Column('z_score', sa.Float(), nullable=True),
    )

    op.add_column(
        'rate_alerts',
        sa.Column('latest_rate', sa.Float(), nullable=True),
    )

    op.add_column(
        'rate_alerts',
        sa.Column('mean_30d', sa.Float(), nullable=True),
    )

    op.add_column(
        'rate_alerts',
        sa.Column(
            'pattern_type',
            sa.String(),
            nullable=False,
            server_default='one_day',
        ),
    )

    op.add_column(
        'rate_alerts',
        sa.Column(
            'duration_days',
            sa.Integer(),
            nullable=False,
            server_default='1',
        ),
    )

    op.add_column(
        'rate_alerts',
        sa.Column('cumulative_magnitude_pct', sa.Float(), nullable=True),
    )

    op.add_column(
        'rate_alerts',
        sa.Column('last_event_date', sa.Date(), nullable=True),
    )

    op.add_column(
        'rate_alerts',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
    )

    op.drop_constraint(
        'uq_alert_rule_eval_date',
        'rate_alerts',
        type_='unique',
    )

    op.drop_column('rate_alerts', 'rule_id')
    op.drop_column('rate_alerts', 'evaluation_date')

    # --------------------------------------------------
    # rate_trends
    # --------------------------------------------------

    op.add_column(
        'rate_trends',
        sa.Column('r_squared', sa.Float(), nullable=True),
    )

    op.drop_column('rate_trends', 'confidence')
    op.drop_column('rate_trends', 'recommendation')
    op.drop_column('rate_trends', 'error_message')
    op.drop_column('rate_trends', 'outlook_text')
    op.drop_column('rate_trends', 'status')

    # --------------------------------------------------
    # route_briefs
    # --------------------------------------------------

    op.drop_column('route_briefs', 'carrier')
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_briefs', sa.Column('carrier', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_route_briefs_user_id', 'route_briefs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('rate_trends', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=False))
    op.add_column('rate_trends', sa.Column('outlook_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rate_trends', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rate_trends', sa.Column('recommendation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rate_trends', sa.Column('confidence', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rate_trends', 'r_squared')
    op.add_column('rate_alerts', sa.Column('evaluation_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('rate_alerts', sa.Column('rule_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_rate_alerts_user_id', 'rate_alerts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_rate_alerts_rule_id', 'rate_alerts', 'rate_alert_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_alert_rule_eval_date', 'rate_alerts', ['rule_id', 'evaluation_date'])
    op.drop_column('rate_alerts', 'updated_at')
    op.drop_column('rate_alerts', 'last_event_date')
    op.drop_column('rate_alerts', 'cumulative_magnitude_pct')
    op.drop_column('rate_alerts', 'duration_days')
    op.drop_column('rate_alerts', 'pattern_type')
    op.drop_column('rate_alerts', 'mean_30d')
    op.drop_column('rate_alerts', 'latest_rate')
    op.drop_column('rate_alerts', 'z_score')
    op.drop_column('rate_alerts', 'direction')
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('rate_alert_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trade_lane', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('magnitude_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_usd', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_rate_alert_rules_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='rate_alert_rules_pkey')
    )
    op.create_index('idx_rules_user_active', 'rate_alert_rules', ['user_id', 'is_active'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='api_keys_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='api_keys_pkey'),
    sa.UniqueConstraint('key_hash', name='api_keys_key_hash_key')
    )
    # ### end Alembic commands ###
