"""create initial 6 tables

Revision ID: 9d518c84d358
Revises: 
Create Date: 2026-08-04 03:45:39.160586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d518c84d358'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_advisories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('advisory_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('affected_lanes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freight_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('trade_lane', sa.String(), nullable=False),
    sa.Column('origin_port', sa.String(), nullable=False),
    sa.Column('dest_region', sa.String(), nullable=False),
    sa.Column('container_type', sa.String(), nullable=False),
    sa.Column('rate_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'trade_lane', 'container_type', 'rate_date', name='uq_freight_rate')
    )
    op.create_table('port_congestion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('port_code', sa.String(), nullable=False),
    sa.Column('port_name', sa.String(), nullable=False),
    sa.Column('congestion_index', sa.Float(), nullable=True),
    sa.Column('avg_dwell_days', sa.Float(), nullable=True),
    sa.Column('vessels_waiting', sa.Integer(), nullable=True),
    sa.Column('advisory_text', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trade_lane', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('magnitude_pct', sa.Float(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_lane', sa.String(), nullable=False),
    sa.Column('computed_date', sa.Date(), nullable=False),
    sa.Column('avg_7d_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_30d_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('change_7d_pct', sa.Float(), nullable=True),
    sa.Column('change_30d_pct', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('slope_per_week', sa.Float(), nullable=True),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_lane', 'computed_date', name='uq_rate_trend')
    )
    op.create_table('route_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('cargo_type', sa.String(), nullable=False),
    sa.Column('brief_markdown', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_briefs')
    op.drop_table('rate_trends')
    op.drop_table('rate_alerts')
    op.drop_table('port_congestion')
    op.drop_table('freight_rates')
    op.drop_table('carrier_advisories')
    # ### end Alembic commands ###
