"""add_rate_outlook_fields

Revision ID: dc23342acfef
Revises: 83b6a5ce207d
Create Date: 2026-08-16 03:13:40.106081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc23342acfef'
down_revision: Union[str, Sequence[str], None] = '83b6a5ce207d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_trends', sa.Column('outlook_text', sa.String(), nullable=True))
    op.add_column('rate_trends', sa.Column('recommendation', sa.String(), nullable=True))
    op.add_column('rate_trends', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('rate_trends', sa.Column('status', sa.String(), server_default='none', nullable=False))
    op.add_column('rate_trends', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_trends', 'error_message')
    op.drop_column('rate_trends', 'status')
    op.drop_column('rate_trends', 'confidence')
    op.drop_column('rate_trends', 'recommendation')
    op.drop_column('rate_trends', 'outlook_text')
    # ### end Alembic commands ###
